/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package OpenZWave;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RemoteValueGenre implements org.apache.thrift.TEnum {
  ValueGenre_Basic(0),
  ValueGenre_User(1),
  ValueGenre_Config(2),
  ValueGenre_System(3),
  ValueGenre_Count(4);

  private final int value;

  private RemoteValueGenre(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RemoteValueGenre findByValue(int value) { 
    switch (value) {
      case 0:
        return ValueGenre_Basic;
      case 1:
        return ValueGenre_User;
      case 2:
        return ValueGenre_Config;
      case 3:
        return ValueGenre_System;
      case 4:
        return ValueGenre_Count;
      default:
        return null;
    }
  }
}
