/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace OpenZWave
{
  public enum DriverControllerCommand
  {
    ControllerCommand_None = 0,
    /// <summary>
    /// < No command.
    /// </summary>
    ControllerCommand_AddController = 1,
    /// <summary>
    /// < Add a new controller to the Z-Wave network.  The new controller will be a secondary.
    /// </summary>
    ControllerCommand_AddDevice = 2,
    /// <summary>
    /// < Add a new device (but not a controller) to the Z-Wave network.
    /// </summary>
    ControllerCommand_CreateNewPrimary = 3,
    /// <summary>
    /// < Add a new controller to the Z-Wave network.  The new controller will be the primary, and the current primary will become a secondary controller.
    /// </summary>
    ControllerCommand_ReceiveConfiguration = 4,
    /// <summary>
    /// < Receive Z-Wave network configuration information from another controller.
    /// </summary>
    ControllerCommand_RemoveController = 5,
    /// <summary>
    /// < Remove a controller from the Z-Wave network.
    /// </summary>
    ControllerCommand_RemoveDevice = 6,
    /// <summary>
    /// < Remove a new device (but not a controller) from the Z-Wave network.
    /// </summary>
    ControllerCommand_RemoveFailedNode = 7,
    /// <summary>
    /// < Move a node to the controller's failed nodes list. This command will only work if the node cannot respond.
    /// </summary>
    ControllerCommand_HasNodeFailed = 8,
    /// <summary>
    /// < Check whether a node is in the controller's failed nodes list.
    /// </summary>
    ControllerCommand_ReplaceFailedNode = 9,
    /// <summary>
    /// < Replace a non-responding node with another. The node must be in the controller's list of failed nodes for this command to succeed.
    /// </summary>
    ControllerCommand_TransferPrimaryRole = 10,
    /// <summary>
    /// < Make a different controller the primary.
    /// </summary>
    ControllerCommand_RequestNetworkUpdate = 11,
    /// <summary>
    /// < Request network information from the SUC/SIS.
    /// </summary>
    ControllerCommand_RequestNodeNeighborUpdate = 12,
    /// <summary>
    /// < Get a node to rebuild its neighbour list.  This method also does ControllerCommand_RequestNodeNeighbors
    /// </summary>
    ControllerCommand_AssignReturnRoute = 13,
    /// <summary>
    /// < Assign a network return routes to a device.
    /// </summary>
    ControllerCommand_DeleteAllReturnRoutes = 14,
    /// <summary>
    /// < Delete all return routes from a device.
    /// </summary>
    ControllerCommand_CreateButton = 15,
    /// <summary>
    /// Create a handheld button id.
    /// </summary>
    ControllerCommand_DeleteButton = 16,
  }
}
