/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ozw_CONSTANTS_H
#define ozw_CONSTANTS_H

#include "ozw_types.h"

namespace OpenZWave {

class ozwConstants {
 public:
  ozwConstants();

};

extern const ozwConstants g_ozw_constants;

} // namespace

#endif
